//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerOrdersPlatform.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int Detail_ID { get; set; }
        public int Order_ID { get; set; }
        public string Product_SKU { get; set; }
        public int Amount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
