//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerOrdersPlatform.Persistence.OrderDetails
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomerOrdersEntitiesOrderDetails : DbContext
    {
        public CustomerOrdersEntitiesOrderDetails()
            : base("name=CustomerOrdersEntitiesOrderDetails")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Order_Details> Order_Details { get; set; }
    }
}
